version: "3.7"
services:
  web1:
    build: ./quote_gen
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
  web2:
    build: ./quote_disp
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - web1
