version: "3.7"
services:
  web1:
    build: ./quote_gen
    deploy:
      replicas: 2
    ports:
      - "5001-5002:5000"
    restart: always
    volumes:
    - ./quote_gen:/app
  web2:
    build: ./quote_disp
    ports:
      - "6001:5001"
    restart: always
    volumes:
    - ./quote_disp:/app
    depends_on:
      - web1